### ISSUE TITLE
Add tooltips

### ISSUE THREAD

**Issue by aioue** [ekonstantinidis/gitify#100]
Search, Settings and Logout icons should have tooltips when hovered over for a second or so.

**Comment by ekonstantinidis** [comment]
Tooltips added in #102  :smile:

**Comment by aioue** [comment]
Great stuff!

Further enhancement, for tooltips on:

- Exclamation symbol
- Question mark symbol
- PR
- "Mark all repo as read" tick icon

**Comment by ekonstantinidis** [comment]
Even more tooltips added on #126
