### ISSUE TITLE
Mark read on click

### ISSUE THREAD

**Issue by Naatan** [ekonstantinidis/gitify#101]
Seems at the moment you have to manually dismiss notifications. Would be nice if there was an option to do that automatically when you press one.

**Comment by aioue** [comment]
Prefer the existing gitify behaviour - don't like it when the github notifications automatically clear themselves.

If this suggestion is going to be included please make it a toggle option. The existing behaviour works well for some people's workflows.

**Comment by ekonstantinidis** [comment]
@Naatan I have to agree with @aioue. Many notifications are important and if they are marked as read, once you click them, they will be gone forever. Guess we can leave this issue open for more opinions on this one?

**Comment by Naatan** [comment]
That's why I'm suggesting it be a preference. I understand it's useful for some peoples workflow.

**Comment by ekonstantinidis** [comment]
Great! Will see if I can find some time in the weekend to make a setting for it :+1:

**Comment by Naatan** [comment]
Awesome, thank you! :)

**Comment by ekonstantinidis** [comment]
That was easier than I thought @Naatan ! It's ready on #105 . Ready for next release :smile: 
<img width="417" alt="screen shot 2015-10-17 at 02 37 03" src="https://cloud.githubusercontent.com/assets/6333409/10556324/26868cf2-7478-11e5-9020-b6e9d7ca994a.png">

**Comment by ekonstantinidis** [comment]
@Naatan Just released a new version (0.0.18) which includes that setting! Hope you like it!

**Comment by Naatan** [comment]
Perfect, thank you! Minor feedback: I see the previous item disappear as I reopen the menu, if I'm fast enough I see the animation. I guess you're waiting for a response to remove it.
