### ISSUE TITLE
Notifications should indicate what type they are

### ISSUE THREAD

**Issue by aioue** [ekonstantinidis/gitify#110]
Menu has icons that notifications do not have.

Would be great to know if something is a PR or issue, tag when notification appears.

**Comment by ekonstantinidis** [comment]
Ready for next release :smile: Support for Issues, Pull Requests and Commits.
<img width="425" alt="screen shot 2015-12-09 at 19 13 03" src="https://cloud.githubusercontent.com/assets/6333409/11695815/1298eb4e-9ea9-11e5-80a1-c2ea52920017.png">
<img width="388" alt="screen shot 2015-12-09 at 19 14 16" src="https://cloud.githubusercontent.com/assets/6333409/11695816/129c2994-9ea9-11e5-80b8-73daaffd3dbc.png">

**Comment by aioue** [comment]
Looks really great!

**Comment by ekonstantinidis** [comment]
Another example :smiley:  
<img width="414" alt="screen shot 2015-12-09 at 19 17 11" src="https://cloud.githubusercontent.com/assets/6333409/11695899/85ac0148-9ea9-11e5-994e-35757433d3ff.png">
