### ISSUE TITLE
Please port to Windows

### ISSUE THREAD

**Issue by KamranMackey** [ekonstantinidis/gitify#111]
This looks like a really awesome tool, and I would love it if it was ported to Windows, since you would get a lot more users, especially considering the size of Windows' popularity/user base.

**Comment by Braunson** [comment]
:+1:

**Comment by mrmlnc** [comment]
I started working on this.

![image](https://cloud.githubusercontent.com/assets/7034281/10949985/ac7882c0-8346-11e5-8e60-f1f49e4b90fa.png)

**Comment by ekonstantinidis** [comment]
That's awesome @mrmlnc ! Can't wait to test it! :+1:

**Comment by mrmlnc** [comment]
Yeap! It works on Mint :P
![image](https://cloud.githubusercontent.com/assets/7034281/10968272/4489e448-83d1-11e5-8963-642d21041cb0.png)

**Comment by ekonstantinidis** [comment]
I'm going to close this one and track #128 since it includes all the other updates like - React `0.14.3`, React Router `1.0.1` etc.
