### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by piclez** [ekonstantinidis/gitify#115]
Hello, very nice project.

I ran my local version (npm install) and all I get after I click the icon from the menu bar is a white screen. Any ideas how to debug this? I'm not watching the src since it got an error when installing via 'npm run watch'.

Thanks.

Peter

**Comment by ekonstantinidis** [comment]
Hello @piclez! You can find all the instruction you need to run the project locally at https://github.com/ekonstantinidis/gitify#development .

Particularly make sure you run:

    npm run build  # OR `npm run watch` which also builds the project
    npm start  # To start the app

One more thing that will allow you to login, is to use the client id and secret key as explained in the above link (just copy, paste and re-build).

Let me know if you need further help!

**Comment by piclez** [comment]
Thanks @ekonstantinidis! I just had to install grunt-cli.
Really cool!

One last question, when I run via npm start and close and run it again the settings like "On Click, Mark as Read" are lost. Is this something it will work only when running the App?

Thanks.

**Comment by ekonstantinidis** [comment]
Hello @piclez ! I'm not 100% but yes I think the settings are being erased every time you are running `npm start`. I can confirm that if you package your app then your settings will be stored.
