### ISSUE TITLE
npm run package fails

### ISSUE THREAD

**Issue by piclez** [ekonstantinidis/gitify#116]
I'm getting this error when trying to build the package:

    11 silly lifecycle gitify@0.0.18~package: Args: [ '-c',
    11 silly lifecycle   'electron-packager . Gitify --overwrite --platform=darwin --arch=x64 --version=0.32.3 --asar=true --icon=images/app-icon.icns --prune --ignore=\'src\' --ignore=\'coverage\'' ]
    12 silly lifecycle gitify@0.0.18~package: Returned: code: 1  signal: null
    13 info lifecycle gitify@0.0.18~package: Failed to exec package script
    14 verbose stack Error: gitify@0.0.18 package: `electron-packager . Gitify --overwrite --platform=darwin --arch=x64 --version=0.32.3 --asar=true --icon=images/app-icon.icns --prune --ignore='src' --ignore='coverage'`
    14 verbose stack Exit status 1
    14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
    14 verbose stack     at emitTwo (events.js:87:13)
    14 verbose stack     at EventEmitter.emit (events.js:172:7)
    14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
    14 verbose stack     at emitTwo (events.js:87:13)
    14 verbose stack     at ChildProcess.emit (events.js:172:7)
    14 verbose stack     at maybeClose (internal/child_process.js:818:16)
    14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

Also, npm tests are failing but I think this is not related:

    Using Jest CLI v0.4.18
    FAIL  src/js/__tests__/components/login.js
    TypeError: Cannot read property 'length' of undefined
     at maybeReadMore_ (_stream_readable.js:430:18)

**Comment by ekonstantinidis** [comment]
Can you confirm which version of node are you on? I'll soon merge a PR that updates `jest-cli` to 0.8.0 and will work with `node v4.2.0`.

About running the app with `npm start` can also try removing the `node_modules/` directory, install node `4.2.0` and then run `npm install` again?
