### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by rntgspr** [ekonstantinidis/gitify#117]
Hi, nice project,

I am trying to add github account trough a proxy, nothing happens on login window.

Seen's it aren't using system proxy.

**Comment by RealOrangeOne** [comment]
This sounds more like a bug with electron than with Gitify. Alternatively it could be a problem with your OS

**Comment by ekonstantinidis** [comment]
Sorry for the late reply @rntgspr! Looks like it's not a gitify issue so will close this one for now.
