### ISSUE TITLE
Add homebrew cask install method to README

### ISSUE THREAD

**Issue by brandonb927** [ekonstantinidis/gitify#135]
I typed out a lengthy description before even attempting it, but you *can* install this via homebrew cask!

![](http://i.giphy.com/Yp8GKgfytxQVq.gif)

It would be great to have this in the README :smile:

**Comment by ekonstantinidis** [comment]
Hello @brandonb927 ! Yes it has been a while since it was added to cask (it was like ages ago - I even forgot about it). Will open a PR soon - feel free to open one yourself!  :smile:
