### ISSUE TITLE
Fonts are too big

### ISSUE THREAD

**Issue by tristanbes** [ekonstantinidis/gitify#138]
Hello,

When having multiple organizations & projects, I have a lot of notification.
Right now it's difficult because fonts are too big and the organization name are way too big too.

**Comment by ekonstantinidis** [comment]
I think you are right - The Organisation name/Repository name font size could be a bit smaller! Will give it a go and see how it looks!

**Comment by ekonstantinidis** [comment]
Fixed in #140.
