### ISSUE TITLE
less intrusive icon

### ISSUE THREAD

**Issue by wbolster** [ekonstantinidis/gitify#142]
currently the icon looks like three icons: `> g _`. i'd prefer a less intrusive icon. octocat in a chat balloon perhaps?

**Comment by kaicataldo** [comment]
Sadly, GitHub doesn't allow this: https://github.com/logos. But I'd love to see an alternate logo as well - thoughts on using/incorporating the git logo? https://git-scm.com/downloads/logos

**Comment by ekonstantinidis** [comment]
Hello there @wbolster ! Sorry for the late reply. The new logo is now on master and it's ready for the next release!

![https://cloud.githubusercontent.com/assets/6333409/15630661/6c0bad78-253c-11e6-80e6-2ee1a8da6e6a.png](https://cloud.githubusercontent.com/assets/6333409/15630661/6c0bad78-253c-11e6-80e6-2ee1a8da6e6a.png)

**Comment by wbolster** [comment]
thanks!
