### ISSUE TITLE
Can't paste password into GitHub Login

### ISSUE THREAD

**Issue by richrace** [ekonstantinidis/gitify#15]
So I use a generated 1Password password for GitHub. And I can't paste it into the login window.

Not sure if it's this app or Electron.

**Comment by ekonstantinidis** [comment]
You are right @richrace ! It has to do with Electron. It's actually a `BrowserWindow` and it seems that Electron prevents copying & pasting. Will have a look later today!

**Comment by ekonstantinidis** [comment]
Hey @richrace ! You can now copy & paste within the app with [this release](https://github.com/ekonstantinidis/gitify/releases/tag/0.0.10).
