### ISSUE TITLE
Better memory optimizations?

### ISSUE THREAD

**Issue by chiefy** [ekonstantinidis/gitify#155]
I know :no_entry_sign:  about memory opts and electron, but on my system Gitify typically uses ~200-300mb of RAM. Seems kinda high? Is this typical?

**Comment by CBarraford** [comment]
mine is at 187MB, can't speak to if that is high or not, but it seems high ¯\_(ツ)_/¯

**Comment by ekonstantinidis** [comment]
Hi there! Will do some tests with the new version soon. Will also upgrade to Electron 1 so I guess that will help?

**Comment by ekonstantinidis** [comment]
I think electron has improved a lot in Version 1 so I would suggest giving a try with [Gitify 1.0.0](https://github.com/ekonstantinidis/gitify/releases/tag/1.0.0).

Ps. Autoupdate won't work from 0.0.19 to 1.0.0.
