### ISSUE TITLE
npm package fails

### ISSUE THREAD

**Issue by ErikBean** [ekonstantinidis/gitify#158]
I'm getting some weird errors when trying to run `$npm run package`  when it hitsthe `npm prune` command:

Command failed: npm prune --production
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "prune" "--production"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! path /private/var/folders/5g/2f8843ls4d3503htjg6_ccpmnw9s10/T/electron-packager/darwin-x64/Gitify-darwin-x64/Electron.app/Contents/Resources/app/node_modules/.bin/acorn
npm ERR! code EEXIST

npm ERR! Refusing to delete /private/var/folders/5g/2f8843ls4d3503htjg6_ccpmnw9s10/T/electron-packager/darwin-x64/Gitify-darwin-x64/Electron.app/Contents/Resources/app/node_modules/.bin/acorn: is outside /private/var/folders/5g/2f8843ls4d3503htjg6_ccpmnw9s10/T/electron-packager/darwin-x64/Gitify-darwin-x64/Electron.app/Contents/Resources/app/node_modules/acorn and not a link
npm ERR! File exists: /private/var/folders/5g/2f8843ls4d3503htjg6_ccpmnw9s10/T/electron-packager/darwin-x64/Gitify-darwin-x64/Electron.app/Contents/Resources/app/node_modules/.bin/acorn
npm ERR! Move it away, and try again.
/private/var/folders/5g/2f8843ls4d3503htjg6_ccpmnw9s10/T/electron-packager/darwin-x64/Gitify-darwin-x64/Electron.app/Contents/Resources/app/npm-debug.log
[npm-debug copy.log.zip](https://github.com/ekonstantinidis/gitify/files/186654/npm-debug.copy.log.zip)

Any clue what's going on here?
Thanks,
-Erik

**Comment by ekonstantinidis** [comment]
Hello @ErikBean. I'm sorry for the late response - been pretty busy. Do you still have this issue?

**Comment by ErikBean** [comment]
Thanks for replying. No, I'm not even sure I remember what this was about....
