### ISSUE TITLE
Any plans on having a mobile version of gitify?

### ISSUE THREAD

**Issue by gtramontina** [ekonstantinidis/gitify#160]
With push notifications… It would be terrific!

**Comment by ekonstantinidis** [comment]
Hello @gtramontina! I really like the idea and did a bit of research but unfortunately I couldn't find a way of having the GitHub API making a request to a server that will trigger those push notifications.

I guess I could make the phone make a request in the background every minute but it sounds wrong to me. Also we could have a server making a request to the GitHub API for every logged in user every minute which again doesn't sound right. So unfortunately I've got some technical issues with this one.

In the meantime you can check [CodeHub](https://itunes.apple.com/us/app/codehub-github-for-ios/id707173885?ls=1&mt=8) for iOS which is an amazing & open source app. It also has an in-app purchase for push notifications that works great! I think there is something for Android too but not sure about the app name!

**Comment by TimMikeladze** [comment]
It's a workaround but you could integrate pushbullet and make an api call per notification. Would be dependent on the user having the pushbullet app and their computer not being asleep.

**Comment by ekonstantinidis** [comment]
That would require pushbullet and I think there should a better way. Will close this one for now. If anything comes up and there is a way to implement push notifications, I will be really happy to make Gitify with React Native!

**Comment by gtramontina** [comment]
React Native would be awesome…
Also I've heard that we could leverage web-workers and/or service-workers to do this "polling" job and issue local notifications, as opposed to push notifications. I remember reading something around it, but I might be totally wrong…

**Comment by ekonstantinidis** [comment]
Hello everyone! Well, you convinced me (can't resist to new projects/ideas) so gitify-mobile is under development. Will open-source soon and publish to both the AppStore and Google Play Store as soon as there is something that works nice! Until then, you can have a look at some progress! Any ideas, more than welcome!

![img_1926](https://cloud.githubusercontent.com/assets/6333409/15945758/d343ed04-2e8b-11e6-8ec3-17f2ae69a74b.PNG)

![img_1925](https://cloud.githubusercontent.com/assets/6333409/15945757/d3410292-2e8b-11e6-911e-353356b9e395.PNG)

**Comment by ekonstantinidis** [comment]
Good news! The iOS version is currently waiting for review and will hopefully get approved in a couple of days(http://appreviewtimes.com/). Once it gets approved, I'll also submit the Android version too and make the repository public. Fingers crossed!

![img_1935](https://cloud.githubusercontent.com/assets/6333409/16131449/216ebcf0-3406-11e6-8952-374d0fea291f.PNG)

**Comment by gtramontina** [comment]
Thanks a lot for the effort!
How did you go about the notifications?

**Comment by ekonstantinidis** [comment]
Well the first version won't come with push/local notifications. Need to investigate it further - for now you can login, view your notifications, search, open them in app or in browser, choose your settings, pull to refresh etc. Have some ideas for more features but thought I should take it slow..

**Comment by ekonstantinidis** [comment]
Hi there! I've now open-sourced the repository and published the app to the App Store & Google Play Store(looks like it takes Google some time to process the app - should be live very soon). You can find download links in the repo: https://github.com/ekonstantinidis/gitify-mobile 😄

**Comment by gtramontina** [comment]
Installed!! Thank you very much! 😉 🍻

**Comment by gtramontina** [comment]
Soooo smooth so far! Nice designs too… Well done! 👏
