### ISSUE TITLE
Release links breaking

### ISSUE THREAD

**Issue by bgriffith** [ekonstantinidis/gitify#167]
First off great app! Recently I've noticed that links to releases (With the tag icon) have been taking me to the 404 of Github.

One recent such example was this link:
https://github.com/davidkpiano/react-redux-form/releases/3120005

Which was for the release of v0.11.5 of https://github.com/davidkpiano/react-redux-form

Any thoughts?

**Comment by ekonstantinidis** [comment]
Hi @bgriffith! Yes it looks like this is broken. I am currently re-writing the whole app(almost from scratch, react 15, redux etc) so I will fix this one asap. Thank you for reporting this one!

**Comment by bgriffith** [comment]
@ekonstantinidis No problem! Sounds awesome - I'll keep an eye out!

**Comment by kdawgwilk** [comment]
I also am having this problem

**Comment by kdawgwilk** [comment]
This is in 1.0.0

**Comment by ekonstantinidis** [comment]
So I've implemented a temporary patch that won't send you to a 404 page but to the repo's releases. That's because the GitHub Api doesn't return the `html_url` of notifications. Hope it will do for now!
