### ISSUE TITLE
Hide "Star Gitfy on Github" if project has already been starred

### ISSUE THREAD

**Issue by TimMikeladze** [ekonstantinidis/gitify#186]
Hide "Star Gitfy on Github" if project has already been starred. Alternatively, to avoid Github API calls make the text visibility a toggle in the settings. Set it to visible by default.

**Comment by lCharlie123l** [comment]
@ekonstantinidis please

**Comment by ekonstantinidis** [comment]
Ready for next release! 🎉 🎉 🎉 

Gitify checks if the user has starred the repo when the app launches and hides the message conditionally.
