### ISSUE TITLE
Submit 1.0.0 to Homebrew Cask

### ISSUE THREAD

**Issue by ches** [ekonstantinidis/gitify#198]
Hi,

Could you please submit the release to Homebrew Cask? It would be trivial to send a pull request to caskroom myself, but the README has an announcement about changes in the auto-update scheme so I don't know what consequences that may have for the appcast metadata in the formula.

Thanks!

**Comment by ekonstantinidis** [comment]
Hello @ches, unfortunately I am not using cask at all and I wasn't the one who submitted it to cask at first. If you can submit it for me that would be great! Auto-update won't affect this at all. It's just that 0.0.19 won't update to 1.0.0. Thank you!

**Comment by ekonstantinidis** [comment]
Hey! Looks someone updated the cask! Hope it works 😄 
https://github.com/caskroom/homebrew-cask/pull/21982

**Comment by ches** [comment]
Ah yes, thanks for the pointer! It's working for me. I just wasn't sure if the "checkpoint" for appcast would be affected in any way, but apparently it's not an issue.
