### ISSUE TITLE
Window location not updated based on where menubar icon is when OS X/macOS bar hidden

### ISSUE THREAD

**Issue by brandonb927** [ekonstantinidis/gitify#199]
I know the title is a tad confusing, I'm not sure how to describe it in words :(

Here is a picture of what I see when using Bartender app:

![image](https://cloud.githubusercontent.com/assets/1509352/16159250/8a2aa9fa-3476-11e6-940d-eb0a2b4dd490.png)

You can see that the bartender bar covers the app when I click on the Gitify icon in the Bartender bar, and have the OS X menu bar hidden. I've seen other Electron apps fix this so I'm sure it's fixable, not sure how trivial however. I'd be willing to take a dive into a PR if this is not something that is being actively looked into!

Cheers

**Comment by ekonstantinidis** [comment]
Hello @brandonb927 and sorry for the late reply. Unfortunately this seems to be an issue specific to the "Bartender" app since it seems that it works fine with the standard OSX menu bar so I'm not sure there is anything we can do.

**Comment by brandonb927** [comment]
I'm confused by how apps like Dropbox, 1Password, and iStats handle this then...

![image](https://cloud.githubusercontent.com/assets/1509352/18029040/135cd7cc-6c42-11e6-9e91-35d3bdf7c223.png)
![image](https://cloud.githubusercontent.com/assets/1509352/18029043/1e9b5e24-6c42-11e6-85e3-19c8ce8f59d6.png)
![image](https://cloud.githubusercontent.com/assets/1509352/18029051/31c312f8-6c42-11e6-8d2a-4f61af139f8f.png)

I'd be more than happy to take a stab at getting this working in a PR if this is something you'd be interested in supporting.

**Comment by ekonstantinidis** [comment]
I guess that dropbox, 1Password etc are native apps so they handle the window positioning in a much better way, while Gitify is made with electron and there are already some weird calculations which are going to get even worse once we support Windows & Linux. I would suggest waiting for the Windows & Linux support to land and then open a PR?
