### ISSUE TITLE
Improve Spaces / Multiple monitors behaviour 

### ISSUE THREAD

**Issue by richrace** [ekonstantinidis/gitify#20]
So I use multiple spaces.

Given `space_1` and `space_2`
I have Chrome open in `space_1`
When in `space_2` I click on Gitify thenI click on a Repo/PR/Issue it switches to `space_1`, perfect.
However, when I click back on Gitify, it then sends me to `space_2`.

Also, with multiple monitors (`monitor_1`, `monitor_2`).
1. When I open Gitify on `monitor_1`, click again on Gitify
2. Then open Gitify on `monitor_2`, it opens on `monitor_1`
3. Then clicking Gitify again to hide it, and again will show it on `monitor_2`

Again not sure if Electron or not.

**Comment by ekonstantinidis** [comment]
I think that this has to do with Electron. I had a quick look in the Electron API and I couldn't find anything relevant to `getFocusedMonitor` on `TrayClick`. Will have to investigate further.

**Comment by JTarasovic** [comment]
Would [BrowserWindow.setVisibleOnAllWorkspaces(true)](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#browserwindowsetvisibleonallworkspacesvisible) work?

**Comment by ekonstantinidis** [comment]
@JTarasovic I had a look and even though this should help it didn't :cry: Trying to figure it out!

**Comment by ekonstantinidis** [comment]
@richrace This has now been fixed at #82. Thanks! @JTarasovic It seems that what you suggested works great now :+1:
