### ISSUE TITLE
Icon doesn't stay green?

### ISSUE THREAD

**Issue by tylersticka** [ekonstantinidis/gitify#202]
Apologies if this was intended as a feature, but it's been throwing me since I updated to 1.0.0 and I can't tell if it's intentional or not.

When there's a new notification, the menu bar icon turns green. But as soon as I click it and display the app, it loses its color:

<img width="432" alt="screen shot 2016-06-28 at 8 38 59 pm" src="https://cloud.githubusercontent.com/assets/69633/16439774/60c360c2-3d70-11e6-9737-81f1eb3a825c.png">

Notice how I have two unread notifications, but the menu bar icon has lost its hue.

I can't tell if this is a "remove active color on click" feature or if something is wrong. But now it's hard for me to tell if I have unaddressed notifications or not, because the icon color doesn't stick around.

I'm on a retina MacBook Pro, here's my settings screen if that's helpful:

![screen shot 2016-06-28 at 8 40 58 pm](https://cloud.githubusercontent.com/assets/69633/16439813/b02038de-3d70-11e6-96c8-832b979832b8.png)

**Comment by thomasjbradley** [comment]
Yep, I'm having the same problem.
I keep missing notifications because there isn't the constant reminder.

**Comment by ekonstantinidis** [comment]
@tylersticka It's been a long time since I implemented this feature so if I'm correct, this is an intended feature. Once you open the window, the tray because inactive. 

Several people reported the same issue, so maybe it should always stay green if there are any notifications.

I've added this one in for the next release!

**Comment by thomasjbradley** [comment]
Thanks! I'd love it to stay green as long as there are still notifications.

**Comment by ekonstantinidis** [comment]
@tylersticka @thomasjbradley Ready for next release 🎉 🎉 🎉
