### ISSUE TITLE
More obvious UI for clicking?

### ISSUE THREAD

**Issue by richrace** [ekonstantinidis/gitify#21]
Wondering if you had any plans/ideas for making the UI more obvious for what's clickable?

For example:
- Making the cursor become a `pointer`
- Making the blue animation more prominent (didn't really notice)
- Making it more obvious that something is clickable (not really sure how to help other than pointer, but something else UI would be nice, like the blue tick)

**Comment by richrace** [comment]
Eg: https://github.com/richrace/gitify/tree/make-tick-pointer

**Comment by ekonstantinidis** [comment]
I agree - I removed the `pointer` because in the early stages in was look like a website and I wanted to look more like an app. Will improve it for Release 0.0.11.
