### ISSUE TITLE
OS X Dark theme

### ISSUE THREAD

**Issue by jeroenvisser101** [ekonstantinidis/gitify#25]
Gitify doesn't seem to be visible when using the dark theme, it would be nice if that was supported somehow. Will look into this myself tomorrow.

**Comment by jeroenvisser101** [comment]
According to [this](https://github.com/atom/electron/issues/1271) you need to use [template images](https://github.com/atom/electron/blob/master/docs/api/native-image.md#template-image) to support the dark theme.

**Comment by ekonstantinidis** [comment]
Hi @jeroenvisser101 !  Was just reading this one! Looks like it's what we need! Will you give a try or should I?

**Comment by jeroenvisser101** [comment]
If you have time now, it think that's better, because I have a very busy weekend :+1:

**Comment by ekonstantinidis** [comment]
Alright will have a look then!

**Comment by jeroenvisser101** [comment]
Cool! Let me know what you find, and if you need an extra hand, let me know!

**Comment by ekonstantinidis** [comment]
@jeroenvisser101 It was a lot simpler than I thought! Ready for next release! :rocket: 
![screen shot 2015-05-30 at 01 20 05](https://cloud.githubusercontent.com/assets/6333409/7894855/ac18afe8-066a-11e5-99d4-357a7de80c14.png)

**Comment by jeroenvisser101** [comment]
Nice! Thanks for fixing this so fast :+1:
