### ISSUE TITLE
bump a new version with the pull fixes?

### ISSUE THREAD

**Issue by yorkie** [ekonstantinidis/gitify#28]
Hey @ekonstantinidis I found the latest release(0.0.10) is not working with pulls, so I checked you have fixed the bug at 82486461f90354163aea19fa81a04b194f745efb, so if u could create a new zip file with this fixup, that would be that great.

**Comment by ekonstantinidis** [comment]
Hi @yorkie ! Yes you are correct! There are a few more bits (small ones) that I would like to add to the next release, so I'm planning to release a new version tomorrow!

**Comment by yorkie** [comment]
I'm so looking forward the release, love the app so so much :star2:
