### ISSUE TITLE
Distribution via Homebrew-Cask?

### ISSUE THREAD

**Issue by eivind88** [ekonstantinidis/gitify#29]
Any plans for distributing the application binary via [Homebrew-Cask](https://github.com/caskroom/homebrew-cask)?

**Comment by ekonstantinidis** [comment]
Hi @eivind88 ! I have never used it so I'm not the suitable person for this one. Do you have any experience with publishing to homebrew cask?

**Comment by eivind88** [comment]
Not really, but I'll give it a go.

**Comment by eivind88** [comment]
[Done!](https://github.com/caskroom/homebrew-cask/pull/11458)

**Comment by eivind88** [comment]
Mentioned Brew-Cask in readme [(PR)](https://github.com/ekonstantinidis/gitify/pull/34)

**Comment by ekonstantinidis** [comment]
Sounds good! Can you give me some more information on what should be done with every new release?

**Comment by eivind88** [comment]
Sure! You'll need to update version, sha256 (shasum -a 256 LATEST-BINARY.ZIP) and url in [this](https://github.com/caskroom/homebrew-cask/pull/11458/files) file. The entire contribution-process is detailed [here](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md).

**Comment by ekonstantinidis** [comment]
As discussed at #34 we're going with "unofficial" homebrew cask releases for now.

**Comment by ekonstantinidis** [comment]
@eivind88 Just released a new version (Release 0.0.12) so if you want you can submit it to Homebrew Cask!

**Comment by eivind88** [comment]
@ekonstantinidis Updating the cask tonight. Also playing around with some ideas as to how manual updates can be sidestepped.

**Comment by ekonstantinidis** [comment]
@eivind88 That sound great! Thanks for letting me know! Working on some nice stuff and will release an update the next days.
