### ISSUE TITLE
Menu bar icon can't be seen with dark menu bar and dock.

### ISSUE THREAD

**Issue by eivind88** [ekonstantinidis/gitify#33]
The menu bar icon cannot be seen when using dark menu bar and dock on OS X 10.10, as illustrated in the first first attached image (it is to the left of the dropbox-icon).
![skjermbilde 2015-05-31 kl 00 50 02](https://cloud.githubusercontent.com/assets/939844/7899708/16b48628-072f-11e5-99ba-28a23df603d4.png)
It is visible when highlighted (holding the left mouse button).
![skjermbilde 2015-05-31 kl 00 53 29](https://cloud.githubusercontent.com/assets/939844/7899723/aa6c3e2e-072f-11e5-8631-bfea424b0888.png)

**Comment by ekonstantinidis** [comment]
Hi @eivind88 ! This one has been already fixed here #26 ! Will be included in the next release (tomorrow)!
