### ISSUE TITLE
An issue concerning pinch-to-zoom

### ISSUE THREAD

**Issue by jeroenvisser101** [ekonstantinidis/gitify#40]
In electron's windows, pinch to zoom is turned on by default, and it causes you to be able to zoom. I did some research, but it seems like [this question](http://stackoverflow.com/questions/29929411/disable-pinch-zoom-in-webkit-or-electron) is the only one with a working workaround for disabling it.

Not a high-priority, but nice-to-have.

**Comment by ekonstantinidis** [comment]
@jeroenvisser101 You were right! Ready for next release!

**Comment by jeroenvisser101** [comment]
Nice, as always!
