### ISSUE TITLE
Dropdown window is empty

### ISSUE THREAD

**Issue by winkler1** [ekonstantinidis/gitify#43]
Hi-
 I do the "npm start" and the icon appears. Clicking on it drops down an empty frame... all white.

![image](https://cloud.githubusercontent.com/assets/883896/7904364/e121d4ba-07c5-11e5-808b-244b8e842bd2.png)

**Comment by ekonstantinidis** [comment]
Hello, have you builded the project? So in another tab on terminal, do `npm run watch`. This will build the project and watch for changes.

**Comment by semenko** [comment]
Hey, I'm also seeing this with `grunt build && npm build && npm start`

I wonder if it's a node/grunt/npm version issue?

```
~/sandbox/gitify $ grunt --version
grunt-cli v0.1.13
grunt v0.4.5

semenko@focus on master [!?]
~/sandbox/gitify $ npm -version
2.10.1

semenko@focus on master [!?]
~/sandbox/gitify $ node --version
v0.12.4
```

**Comment by semenko** [comment]
And `npm run watch` complains:

```
~/sandbox/gitify $ npm run watch

> gitify@0.0.1 watch /home/semenko/sandbox/gitify
> grunt build && npm build && npm run watch-js | grunt watch

Running "less:main" (less) task
File build/css/style.css created

Running "copy:main" (copy) task
Created 3 directories, copied 27 files

Done, without errors.
Running "watch" task
Waiting...
{ [Error: ENOENT, open 'build/js/app.js'] errno: -2, code: 'ENOENT', path: 'build/js/app.js' }


```

**Comment by ekonstantinidis** [comment]
That sounds weird. So can you try the following:

    npm install
    mkdir -p build/js
    npm run watch
    npm start

There might be an issue with `npm run build` so better to use `npm run watch`. Also make sure `build/js` exists.

**Comment by semenko** [comment]
Ah, awesome! Just making the `build/js` directory fixed it. Thanks! :+1:

**Comment by ekonstantinidis** [comment]
That's great! Will have a look at the `npm scripts` again before the next release.
