### ISSUE TITLE
Retina taskbar icon

### ISSUE THREAD

**Issue by AlecRust** [ekonstantinidis/gitify#44]
Could we get one? Currently it's blurry. Here's a side by side with a retina icon:

![screenshot](https://i.imgur.com/wRAmAdm.png)

**Comment by ekonstantinidis** [comment]
Hi @AlecRust! That sounds good and doable. I've set it for next milestone. Will you be able to test it(clone the repo and use `npm to build`) once it's done (I don't have a retina screen)?

**Comment by ekonstantinidis** [comment]
There is a PR now for Retina Icons! @AlecRust If you can test it (also with dark mode) we can then merge it and release it with 0.0.12.

**Comment by ekonstantinidis** [comment]
Just tested with XCode's graphic tools and works great!
![screen shot 2015-06-01 at 22 30 13](https://cloud.githubusercontent.com/assets/6333409/7923769/fb8e66e0-08ad-11e5-9c5f-0f56cecb1042.png)
![screen shot 2015-06-01 at 22 27 44](https://cloud.githubusercontent.com/assets/6333409/7923770/fb909ab4-08ad-11e5-9327-9b49f5332f3f.png)

**Comment by AlecRust** [comment]
@ekonstantinidis yup, I can confirm this works well. Nice one!

![screenshot](https://i.imgur.com/oqY6KOx.png)
