### ISSUE TITLE
Indicate issue status (open/closed) with icon color

### ISSUE THREAD

**Issue by anandthakker** [ekonstantinidis/gitify#45]
The /notifications list on GH colors the issue and PR icons according to their status, which I find really useful for deciding which issues to jump to / read first.

**Comment by ekonstantinidis** [comment]
Hi @anandthakker! Unfortunately the payload from the GitHub API does not give any information regarding the state of PRs and Issues. It would be really useful to have but our hands are tight.

I would be more than happy to implement such functionality if the API gets updated at some point.

**Comment by anandthakker** [comment]
Ah -- totally understandable.  Thanks for the super handy tool!
