### ISSUE TITLE
Live Reload for development

### ISSUE THREAD

**Issue by ekonstantinidis** [ekonstantinidis/gitify#54]

**Comment by whoisandie** [comment]
Sounds good. How about using gulp in dev environment, to manage the build process? Just as a reference, heres the gulpfile for the project ive been working on lately. https://github.com/whoisandie/yoda/blob/master/gulpfile.js

**Comment by ekonstantinidis** [comment]
That's interesting - will have to move from `grunt` to `gulp` but that's ok. Currently testing a new version with some major features(sounds and native notifications) so will set for next release!

**Comment by whoisandie** [comment]
Sounds good 👍

**Comment by ekonstantinidis** [comment]
Tried webpack but had issues with octicons so I sticked back to gulp & browserify. Will close this one for now.
