### ISSUE TITLE
Change icon color if opened since last new notification

### ISSUE THREAD

**Issue by JakeSidSmith** [ekonstantinidis/gitify#70]
Would be good if the Gitify icon returned to black after you open it.

Basically only make it turn green if there are notifications you haven't seen before. :)

**Comment by ekonstantinidis** [comment]
@JakeSidSmith Sounds good and should be pretty easy to fix. Just like https://github.com/ekonstantinidis/gitify/blob/master/main.js#L38 we can do something like: 

    appIcon.window.on('focus', function () {
      appIcon.setImage(iconIdle);
    );

**Comment by ekonstantinidis** [comment]
Will close it for now since I think that it should always be *green* if there are unread notifications? Same like github.com - you can see the notifications but the icon is always there until you mark them as read.

**Comment by JakeSidSmith** [comment]
I guess. Consistency is best. :)
