### ISSUE TITLE
Instantly remove seen notifications

### ISSUE THREAD

**Issue by JakeSidSmith** [ekonstantinidis/gitify#71]
After clicking the tick on a notification, it'd be nice if it animated itself out & disappeared.

**Comment by ekonstantinidis** [comment]
@JakeSidSmith You got it? Or should I give it a try?

**Comment by JakeSidSmith** [comment]
I'd quite like to give this a go, but it depends if I have time. :)

**Comment by JakeSidSmith** [comment]
Nice. :rocket:
