### ISSUE TITLE
Application doesn't acknowledge auth?

### ISSUE THREAD

**Issue by mrmechko** [ekonstantinidis/gitify#87]
Once I've gone through the OAuth process, first time loading the app on OS X, I get a little window with `OAuth application authorized` in the header and an empty body.  Clicking the app from the menubar again just asks me to login again.  Image attached.
![gitifyerror](https://cloud.githubusercontent.com/assets/1429154/9425974/5c473a44-48f4-11e5-8938-24f699794708.png)

1. What can I do to rectify the situation?
2. What can be done to avoid this in the future?

**Comment by ekonstantinidis** [comment]
Hi @mrmechko! Can you confirm which version are you using so I can further investigate the issue?

**Comment by mrmechko** [comment]
Hi @ekonstantinidis I'm using v0.0.14 on OS X (latest version, whatever that is, I updated last night).

**Comment by ekonstantinidis** [comment]
Right! So I fixed that bug in #88 and will release a new version asap (probably by tomorrow)!

**Comment by mrmechko** [comment]
Awesome! I'm really excited to be able to use this. It looks beautiful.

**Comment by ekonstantinidis** [comment]
I've just released a new version ([0.0.15](https://github.com/ekonstantinidis/gitify/releases/tag/0.0.15)) which fixes this bug so everything should be ok now :smile: Let me know how it goes and thanks for open this issue. Cheers @mrmechko!

Ps. Planning to release a major update next week!

**Comment by mrmechko** [comment]
Works now.  (I promise I don't have another notification app installed. I just happened to log in as you published it)
