### ISSUE TITLE
Show blank window on try to login after logout.

### ISSUE THREAD

**Issue by chocopie116** [ekonstantinidis/gitify#92]
awesome application.
found some bug that try to login after logout.
(under OSX 10.10.3)

plz take a look 
![image](https://cloud.githubusercontent.com/assets/787955/9923115/c40b1db2-5d2b-11e5-8b1f-442201733dfd.png)

**Comment by ekonstantinidis** [comment]
Hello @chocopie116! Can you confirm if you are using the latest version `0.0.16`?

**Comment by ekonstantinidis** [comment]
Hey @chocopie116! Will release a new version today that includes a fix for this one (#93). Thanks for letting me know :tada:
