### ISSUE TITLE
Clicking on OS X notification causes menu to appear far away from gitify icon

### ISSUE THREAD

**Issue by aioue** [ekonstantinidis/gitify#99]
Clicked on OS X notification on the right hand side and menu appeared over to the left of the screen.

![screen shot 2015-10-16 at 14 44 32](https://cloud.githubusercontent.com/assets/1254905/10543135/a035adda-7414-11e5-96ca-5704daf91de4.png)

**Comment by ekonstantinidis** [comment]
I think that this is happening only when you first open gitify and click on a notification without clicking on the tray icon which sets the window's position. I think we should set a default position (top-right corner) if you haven't clicked on the tray and the position hasn't been calculated yet.

Ps. This will also help with the linux version - *currently* you can't calculate the tray icon's position on linux.

**Comment by aioue** [comment]
It's done it again. This time in the middle of the screen.

![image](https://cloud.githubusercontent.com/assets/1254905/11013669/16dcafc4-850e-11e5-9c22-36c356a4a223.png)

**Comment by aioue** [comment]
happens every time.

![image](https://cloud.githubusercontent.com/assets/1254905/11013672/59320d4c-850e-11e5-9e8d-1a602f6ed991.png)

**Comment by ekonstantinidis** [comment]
Hi @aioue ! Can you confirm which version are you on? Is it the latest(0.0.18) - does it have "On Click, Mark as Read" under settings?

Ps. Will add the version number in the settings page on the next release :)

**Comment by aioue** [comment]
@ekonstantinidis Yes I am on the latest auto updating release.

Just happened again. I believe it may be a symptom of moving from 2 screens to 1 but cannot reproduce steps.

![image](https://cloud.githubusercontent.com/assets/1254905/11262296/4159e4b8-8e75-11e5-947e-df1d29c462e3.png)
